languageCode = "en-us"
title = "Learn Blazor"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn" 

# For search functionnality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  editURL = "https://github.com/software-architects/learn-blazor/tree/master/content/"
  author = "Rainer Stropek"
  description = "Website with learning resources regarding the Blazor platform"
  disableLanguageSwitchingButton = true
  themeVariant = "blue"
  disclaimer = "The *learn-blazor* site had been created at a point in time when there was no Blazor documentation at all available. Since then, the framework has grown and matured a lot. Documentation [is now available on docs.microsoft.com](https://docs.microsoft.com/en-us/aspnet/core/blazor/). Therefore, much of the content of *learn-blazor* isn't necessary anymore and parts of it are outdated. I hope the site was useful to early adopters. Open [Microsoft's documentation of Blazor...](https://docs.microsoft.com/en-us/aspnet/core/blazor/)"

[[menu.shortcuts]] 
name = "<i class='fa fa-github'></i> Blazor on GitHub"
identifier = "bg"
url = "https://github.com/aspnet/aspnetcore"
weight = 10

[[menu.shortcuts]] 
name = "<i class='fa fa-code'></i> Blazor Docs"
identifier = "do"
url = "https://blazor.net/docs/"
weight = 35

[[menu.shortcuts]] 
name = "<i class='fa fa-bullhorn'></i> Terms of Service"
identifier = "ts"
url = "/terms-of-service"
weight = 40
